- name: Install pip
  apt: name=python-pip state=present
- name: Install redis
  apt: name=redis-server state=present
- name: Install python dev headers
  apt: name=python-dev
- name: Install ssl dev headers
  apt: name=libssl-dev
- name: Install libxml2 headers
  apt: name=libxml2-dev
- name: Install libxslt headers
  apt: name=libxslt-dev
- name: Install gnuplot
  apt: name=gnuplot
- name: Install clisp
  apt: name=clisp
- name: Install automake
  apt: name=automake
- name: Install pstotext
  apt: name=pstotext
- name: Install gettext
  apt: name=gettext
- name: Install mysql client
  apt: name=libmariadbclient-dev
- name: Install cython
  apt: name=cython
- name: Install libhdf5
  apt: name=libhdf5-dev

# Install packages
- name: Install pypi requirements
  pip: chdir={{invenio_srcdir}} requirements=requirements.txt state=present
- name: Install plumbum
  pip: name=plumbum state=present
- name: Install invenio devserver
  pip: name=invenio-devserver state=present
- name: Install nose tests
  pip: name=nose state=present
- name: Start/Enable redis
  service: name=redis-server enabled=yes state=started

- name: Remove installed invenio
  file: path={{invenio_prefix}} state=absent
  when: files_reinstall
- name: Make distclean
  command: chdir={{invenio_srcdir}} make distclean removes={{invenio_srcdir}}/Makefile
  ignore_errors: yes
  when: files_reinstall
- name: Create /opt/invenio
  file: path={{invenio_prefix}} owner=vagrant group=vagrant state=directory
- name: Run autotools
  script: scripts/autoremake.sh creates={{invenio_srcdir}}/Makefile
  sudo: false
- name: Make invenio
  command: chdir={{invenio_srcdir}} make creates={{invenio_srcdir}}/modules/miscutil/lib/build/temp.linux-x86_64-2.7/intbitset.o
  sudo: false
- name: Create invenio lib dir
  file: path={{invenio_prefix}}/lib owner=vagrant group=vagrant state=directory
- name: Create invenio lib dir
  file: path={{invenio_prefix}}/lib/python owner=vagrant group=vagrant state=directory
- name: Create invenio lib dir
  file: path={{invenio_prefix}}/lib/python/invenio owner=vagrant group=vagrant state=directory
- name: Create invenio symlinks
  file: src={{invenio_prefix}}/lib/python/invenio dest=/usr/local/lib/python2.7/site-packages/invenio state=link
- name: Create invenio symlinks
  file: src={{invenio_prefix}}/lib/python/invenio dest=/usr/lib/python2.7/dist-packages/invenio state=link
- name: Install invenio
  command: chdir={{invenio_srcdir}} make install creates={{invenio_prefix}}/lib/python/invenio/search_engine.py
  sudo: false
- name: Install jquery plugins
  command: chdir={{invenio_srcdir}} make install-jquery-plugins creates={{invenio_prefix}}/var/www/js/jquery.min.js
  sudo: false
