- name: Install portage/package.use/webserver
  copy: src=webserver.use dest=/etc/portage/package.use/webserver

# Install packages
- name: Install pip
  portage: package=dev-python/pip state=present
- name: Install redis
  portage: package=dev-db/redis state=present
- name: Install libxslt
  portage: package=dev-libs/libxslt state=present
- name: Install libxml2
  portage: package=dev-libs/libxml2 state=present
- name: Install nodejs
  portage: package=nodejs state=present
- name: Install plumbum
  pip: name=plumbum state=present
- name: Install nose tests
  pip: name=nose state=present

- name: Start/Enable redis
  service: name=redis enabled=yes state=started

- name: Clone repo
  git: repo=https://github.com/jirikuncar/invenio.git dest=/home/invenio/invenio-pu version=pu
- name: Clone repo
  git: repo=https://github.com/inveniosoftware/invenio-demosite dest=/home/invenio/demosite version=pu

# Uninstall invenio
- name: Remove invenio
  pip: "name=invenio state=absent"
  when: files_reinstall
- name: Remove invenio demosite
  pip: "name=invenio-demosite state=absent"
  when: files_reinstall
- name: Create invenio instance directory
  file: "dest={{ invenio_prefix }}/var/invenio.base-instance state=absent"
- name: Create tmp shared directory
  file: "dest={{ invenio_prefix }}/var/tmp-shared state=absent"
- name: Create tmp directory
  file: "dest={{ invenio_prefix }}/var/tmp state=absent"
- name: Create log directory
  file: "dest={{ invenio_prefix }}/var/log state=absent"
- name: Create run directory
  file: "dest={{ invenio_prefix }}/var/run state=absent"

- name: Install pypi requirements
  pip: "chdir={{invenio_srcdir}} requirements='' extra_args='-e . --allow-all-external --process-dependency-links' state=present"
- name: Install pypi requirements
  pip: "chdir={{demosite_srcdir}} requirements='' extra_args='-e . --allow-all-external --process-dependency-links' state=present"

- name: Pylabel
  command: "chdir={{invenio_srcdir}} pybabel compile -fd invenio/base/translations/"

- name: Install bower
  npm: name=bower global=yes
- name: Install grunt
  npm: name=grunt-cli global=yes

- name: Create invenio instance directory
  file: "dest={{ invenio_prefix }}/var/invenio.base-instance owner={{ invenio_user }} group={{ invenio_group }} state=directory"
- name: Create tmp shared directory
  file: "dest={{ invenio_prefix }}/var/tmp-shared owner={{ invenio_user }} group={{ invenio_group }} state=directory"
- name: Create tmp directory
  file: "dest={{ invenio_prefix }}/var/tmp owner={{ invenio_user }} group={{ invenio_group }} state=directory"
- name: Create log directory
  file: "dest={{ invenio_prefix }}/var/log owner={{ invenio_user }} group={{ invenio_group }} state=directory"
- name: Create run directory
  file: "dest={{ invenio_prefix }}/var/run owner={{ invenio_user }} group={{ invenio_group }} state=directory"
- name: Create data directory
  file: "dest={{ invenio_prefix }}/var/data owner={{ invenio_user }} group={{ invenio_group }} state=directory"
