- name: Install portage/package.use/webserver
  copy: src=webserver.use dest=/etc/portage/package.use/webserver

- name: Install pip
  portage: package=dev-python/pip state=present
- name: Install redis
  portage: package=dev-db/redis state=present

# Install packages
- name: Install pypi requirements
  pip: chdir={{invenio_srcdir}} requirements=requirements.txt state=present
- name: Install invenio devserver
  pip: name=invenio-devserver state=present
- name: Start/Enable redis
  service: name=redis enabled=yes state=started


- name: Remove installed invenio
  file: path={{invenio_prefix}} state=absent
- name: Create /opt/invenio
  file: path={{invenio_prefix}} owner=vagrant group=vagrant state=directory
- name: Run autotools
  script: scripts/autoremake.sh # creates={{invenio_srcdir}}/configure
  sudo: false
- name: Make invenio
  command: chdir={{invenio_srcdir}} make creates={{invenio_srcdir}}/modules/miscutil/lib/build/temp.linux-x86_64-2.7/intbitset.o
  sudo: false
- name: Create invenio lib dir
  file: path={{invenio_prefix}}/lib owner=vagrant group=vagrant state=directory
- name: Create invenio lib dir
  file: path={{invenio_prefix}}/lib/python owner=vagrant group=vagrant state=directory
- name: Create invenio lib dir
  file: path={{invenio_prefix}}/lib/python/invenio owner=vagrant group=vagrant state=directory
- name: Create invenio symlinks
  file: src={{invenio_prefix}}/lib/python/invenio dest=/usr/lib64/python2.7/site-packages/invenio state=link
  sudo: true
- name: Install invenio
  command: chdir={{invenio_srcdir}} make install
  sudo: false
