- name: Locale generation
  locale_gen: name=en_US.UTF-8 state=present

- name: Make sure /var/lib/layman exists
  file: dest=/var/lib/layman state=directory owner=root group=root
- name: Make sure /var/lib/layman/make.conf
  copy: src=layman.conf dest=/var/lib/layman/make.conf force=no

- name: Install eix
  portage: package=eix state=present
- name: Install nano
  portage: package=app-editors/nano state=present

# Make sure portage is up to date
- name: Update portage tree (once a week)
  # script: scripts/emerge-sync.py
  emerge: sync=yes
  notify: Update eix
- name: Update portage
  portage: package=portage update=yes

# Config files
- name: Remove portage/package.use/git
  file: dest=/etc/portage/package.use/git state=absent
- name: Install portage/package.use/gentoo
  copy: src=gentoo.use dest=/etc/portage/package.use/gentoo
- name: Install portage/package.accept_keywords/pip
  copy: src=pip.accept_keywords dest=/etc/portage/package.accept_keywords/pip
- name: Install /etc/portage/make.conf
  copy: src=make.conf dest=/etc/portage/make.conf

# Kernel
- name: Update kernel sources
  portage: package=gentoo-sources update=yes
- name: Copy kernel configuration
  command: cp /usr/src/linux-3.10.7-gentoo-r1/.config /usr/src/linux/.config creates=/usr/src/linux/.config
# - name: Install current kernel sources
#   portage: package=gentoo-sources:3.10.7-r1 state=present
- name: Prepare modules for building virtualbox-guest-additions
  command: chdir=/usr/src/linux make modules_prepare creates=/usr/src/linux/arch/x86/tools/relocs_64.o

# For comfort
- name: Install eix
  portage: package=eix state=present
  notify: Update eix
- name: Install htop
  portage: package=htop state=present
- name: Install rsync
  portage: package=rsync state=present
- name: Install telnet
  portage: package=netkit-telnetd state=present
- name: Install gentoolkit
  portage: package=gentoolkit state=present

- name: Install layman
  portage: package=layman state=present
- name: Install git
  portage: package=dev-vcs/git state=present

# Update packages
- name: Update perl
  portage: package=perl update=yes
  notify: Reinstall broken perl packages
- name: Update world
  portage: package=@world update=yes deep=yes newuse=yes
- name: Remerge packages in preserved-rebuild
  portage: package=@preserved-rebuild
