- name: Install mariadb
  apt: name=mariadb-server state=present

- name: Install my.cnf for vagrant (mariadb config)
  copy: src=my.cnf dest=/home/vagrant/.my.cnf force=no
- name: Install my.cnf for root (mariadb config)
  copy: src=my.cnf dest=/root/.my.cnf force=no
- name: Start/Enable mariadb
  service: name=mysql enabled=yes state=started
