- hosts: all
  sudo: true

  vars:
    invenio_prefix: /usr
    invenio_srcdir: /home/invenio/invenio-pu
    demosite_srcdir: /home/invenio/demosite
    invenio_user: vagrant
    invenio_group: vagrant
    bibtask_user: admin
    files_reinstall: true
    db_reinstall: true

  roles:
    - gentoo
    - database
    - webserver

  handlers:
    - name: Create tables
      command: inveniomanage database create
      sudo: false
      notify: Create demo site
    - name: Create demo site
      command: "inveniomanage demosite create"
      sudo: false
      notify: Load demo records
    - name: Load demo records
      command: "inveniomanage demosite populate"
      sudo: false

  tasks:
    - name: Setup mount point for nfs
      file: dest=/home/invenio state=directory
    - name: Setup invenio path in bashrc
      copy: src=files/bashrc dest=/home/vagrant/.bashrc
    - name: Setup invenio path in bashprofile
      copy: src=files/bash_profile dest=/home/vagrant/.bash_profile
    # mysql-python is required for setting the mysql_user ansible module
    - name: Install mysql-python module
      portage: package=dev-python/mysql-python state=present
    - name: Install node
      portage: package=nodejs state=present
    - name: Set root password to "none"
      mysql_user: name=root password=none check_implicit_admin=yes
    - name: Erase invenio database
      mysql_db: name=invenio state=absent
      when: db_reinstall
    - name: Create invenio database
      mysql_db: name=invenio state=present
    - name: Create invenio user for database
      mysql_user: name=invenio password="my123p$ss" priv="invenio.*:ALL"
    - name: Install default invenio config
      copy: src=files/invenio.cfg dest=/usr/var/invenio.base-instance/invenio.cfg force=no
    - name: Proxy for create tables
      command: echo Checking for tables... creates=/var/lib/mysql/invenio/xtrJOB.frm
      # sudo: false, this command does not need root but the existance of
      # /var/lib/mysql/invenio/xtrJOB.frm can only be checked by root
      notify: Create tables
